graph TD
    Start([Начало]) --> x[x = 0]
    x --> while{x < 1000000}
    while --> |True| left["left_sum = сумма первых трёх цифр<br>(включая нули)"]
    left --> right["right_sum = сумма последних трёх цифр"]
    right --> compare{left_sum == right_sum}
    compare --> |True| print[/Вывод x/] --> increment
    compare --> |False| increment["x = x + 1"]
    while --> |False| End([Конец])
    increment --> while
